question_data = [
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The HTML5 standard was published in 2014.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The first computer bug was formed by faulty wires.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Linus Torvalds created Linux and Git.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The logo for Snapchat is a Bell.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "&quot;Windows NT&quot; is a monolithic kernel.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Ada Lovelace is often considered the first computer programmer.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The open source program Redis is a relational database server.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"category": "Science: Computers",
     "type": "boolean", "difficulty": "medium",
     "question": "AMD created the first consumer 64-bit processor.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "hard",
     "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The Windows 7 operating system has six main editions.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "The first dual-core CPU was the Intel Pentium D.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Android versions are named in alphabetical order.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]
     },
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "hard",
     "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     }
]
